
<div class="col-md-3 ">
    <?php
    if (!is_null($this->messages)) {
        foreach ($this->messages as $message)
            echo $message;
    }
    $loginForm->setAttribute('action', $this->url());
    $loginForm->prepare();
    echo $this->form()->openTag($loginForm);
    echo $this->formCollection($loginForm);
    echo $this->form()->closeTag();
    ?>
    <br>
    <p>Need an account? <a href="registration" >Register</a></p>
</div>
