<div class="col-lg-8">
    <h3><?php   echo $test['title']; ?></h3>
    <p><?php echo $test['content']; ?></p>
    <p>Shared: <?php echo $test['created']; ?></p>
    <p>Author: <?php echo $test['Author'] ;?></p>


</div>
<div class="col-sm-3" style="float: right; border:2px solid whitesmoke; padding:10px; margin-top: 5%">
    Did <strong>Jesus</strong> touch you or your circumctances? Please <a href="/share">Share</a> what happend with us.
</div>