<?php echo $this->doctype(); ?>

<html lang="en">
    <head >
        <title>JTestimony | Testimony of Jesus Christ miracles , wonders & grace </title>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('jtestimony'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>


        <meta name="keywords" content="testimony, miracle, healing, jtestimony, jesus, christ, god, prophets, healing, anointing, church,
              signs, wonders">
        <meta name="title" content="">
        <meta name="description" content="JTestimony.com stands as a mermorial stone. Everone has his story with God, 
              here is the place to share such thing to help each other to know what Jesus has made available to us">

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top " role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li  id="home-nav"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li id="test-nav"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Testimonies') ?></a></li>
                        <li id="share-nav"><a href="<?php echo $this->url('share') ?>"><?php echo $this->translate('Share') ?></a></li>
                        <li id="word-nav"><a href="<?php echo $this->url('words') ?>"><?php echo $this->translate('Words') ?></a></li>
                    </ul>  
                    <?php if (!is_null($this->identity())) { ?>
                    <p class="navbar-text navbar-right"> <a href="#" class="navbar-link" id="logout">Logout</a></p>
                    <p class="navbar-text navbar-right">Signed in as <a href="#" class="navbar-link"><strong><?php echo $identity;?></strong></a></p>
                    <?php }else {?>
                    <p class="navbar-text navbar-right"> <a href="/registration" class="navbar-link">Register</a></p>
                    <p class="navbar-text navbar-right"> <a href="/login" class="navbar-link">Login</a></p>
                    <?php }?>
                </div><!--/.nav-collapse -->

            </div>
        </nav>
        <div class="full-width-image-1"></div>
        
        <div class="container">
            <br>
            
            <?php echo $this->content; ?>
                
            <footer>

                <!-- Le styles -->
                <?php
                echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/testimony.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ?>

                <!-- Scripts -->
                <?php
                echo $this->headScript()
                        ->prependFile($this->basePath() . '/js/testimony.js')
                        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
//                        ->prependFile($this->basePath() . '/js/jquery.min.js')
                        ->prependFile($this->basePath() . '/js/jquery-2.1.1.js')
                        ->prependFile($this->basePath() . '/js/jquery-2.1.1.min.map')
                        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ;
                ?>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
