
<div >
    <h4  class="intro-head">

        The Word of <strong>God</strong> is focused on the works of <strong>Jesus</strong>.
        As He is alive, He is still doing His Works, Mircales, Healing the sick and Raising the dead.
        JTestiony.com will serve as a memorial for remembering <strong>Jesus</strong>'s Works.
    </h4>
</div>
    <div class="col-sm-3" style="float: right; border:2px solid whitesmoke; padding:10px;">
        Did Jesus touch you or your circumctances? Please <a href="/share">Share</a> what happend with us.
    </div>
<div class="index-testimony-list ">
    
    <h2 class="index-testimony-header">Latest Testimonies</h2>
    <?php foreach ($tests as $test) { ?>
    <div class="index-testimony-title">
    <h4>    <?php echo $test['title'] ?></h4>
           
    </div>

    <div class="index-testimony-body">
        <p> <?php echo $test['content'] ?></p>
    </div>
    <a href="/testimony/<?php echo $test['id'] ?>" class="index-continue">continue reading...</a>
    <hr>
<?php } ?>
</div>
