<div class="row">
    <div class="col-md-12">
      <div class="main-icon text-success"><span class="uxicon uxicon-clock-refresh"></span></div>
      <h1>"The testimony of Jesus is the spirit of prophecy" REV 19:10</h1>
      <p class="lead">This site is dedicated to talk about the Grace of Jesus Christ and HIS Miracles</p>
      <p class="lead">The site should be built soon... until that you are welcomed to contact us at info@jtestimony.com</p>
    </div>
  </div>