<div class="panel panel-default">
   
    <div class="panel-heading">Users</div>
   
   
    <table class="table">
        <thead><tr>
            <th>#</th>
            <th>Name</th>
            <th>Email</th>

        </tr>
        </thead>
        <tbody>
        <?php foreach ($users as $user) { ?>
            <tr>
                <td><?php echo $user['id'] ?></td>
                <td><?php echo $user['full_name'] ?></td>
                <td><?php echo $user['email'] ?></td>
            </tr>
        <?php } ?>
            </tbody>
    </table>
</div>